/* Generated By:JJTree: Do not edit this line. ASTArraySize.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package yal; 

public
class ASTArraySize extends SimpleNode {
  public ASTArraySize(int id) {
    super(id);
  }

  public ASTArraySize(yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8d2338892ef3b100be8a11d791d3e237 (do not edit this line) */
