/* Generated By:JJTree: Do not edit this line. ASTAssign.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package yal; 

public
class ASTAssign extends SimpleNode {
  public ASTAssign(int id) {
    super(id);
  }

  public ASTAssign(yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=09d43e5ce8e52f431e8d3cc6913eebda (do not edit this line) */
