/* Generated By:JJTree: Do not edit this line. ASTbuildSymbolTable.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package yal;

public
class ASTbuildSymbolTable extends SimpleNode {
  public ASTbuildSymbolTable(int id) {
    super(id);
  }

  public ASTbuildSymbolTable(yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=70d87cdce9fe85762d052e034e051977 (do not edit this line) */
