/* Generated By:JJTree: Do not edit this line. ASTcheckComparisonTypes.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package yal;

public
class ASTcheckComparisonTypes extends SimpleNode {
  public ASTcheckComparisonTypes(int id) {
    super(id);
  }

  public ASTcheckComparisonTypes(yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0b5b9ff38229759047f7b7085fff7c00 (do not edit this line) */
