/* Generated By:JJTree: Do not edit this line. ASTcheckComparisonTypes.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package yal;

public
class ASTcheckComparisonTypes extends SimpleNode {
  public ASTcheckComparisonTypes(int id) {
    super(id);
  }

  public ASTcheckComparisonTypes(yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1bfc0f16ab7c3ea46789d4246e942f4e (do not edit this line) */
