/* Generated By:JJTree: Do not edit this line. ASTcheckArithmeticJavaBytecodes.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package yal;

public
class ASTcheckArithmeticJavaBytecodes extends SimpleNode {
  public ASTcheckArithmeticJavaBytecodes(int id) {
    super(id);
  }

  public ASTcheckArithmeticJavaBytecodes(yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=73fbf2d4046efa2b7b25f3b6af33c5f3 (do not edit this line) */
