/* Generated By:JJTree: Do not edit this line. ASTcheckReturnVariable.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package yal;

public
class ASTcheckReturnVariable extends SimpleNode {
  public ASTcheckReturnVariable(int id) {
    super(id);
  }

  public ASTcheckReturnVariable(yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=192facec8fb56a44f966acbc128e47d3 (do not edit this line) */