/* Generated By:JJTree: Do not edit this line. ASTcheckComparisonTypes.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package yal;

public
class ASTcheckComparisonTypes extends SimpleNode {
  public ASTcheckComparisonTypes(int id) {
    super(id);
  }

  public ASTcheckComparisonTypes(yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9fc19bd285d29ecaba8c92de740ea2eb (do not edit this line) */
