/* Generated By:JJTree: Do not edit this line. ASTclinitJavaBytecodes.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package yal;

public
class ASTclinitJavaBytecodes extends SimpleNode {
  public ASTclinitJavaBytecodes(int id) {
    super(id);
  }

  public ASTclinitJavaBytecodes(yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=21db9df08fedf5cd34c598a60d764816 (do not edit this line) */
