/* Generated By:JJTree: Do not edit this line. ASTFunction.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package yal;

public
class ASTFunction extends SimpleNode {

	public ASTFunction(int id) {
		super(id);
	}

	public ASTFunction(yal2jvm p, int id) {
		super(p, id);
	}

}
/* JavaCC - OriginalChecksum=960d7fdeabca8f1d6cc1627ee5a17f15 (do not edit this line) */
