/* Generated By:JJTree: Do not edit this line. ASTfunctionCallJavaBytecodes.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package yal;

public
class ASTfunctionCallJavaBytecodes extends SimpleNode {
  public ASTfunctionCallJavaBytecodes(int id) {
    super(id);
  }

  public ASTfunctionCallJavaBytecodes(yal2jvm p, int id) {
    super(p, id);
  }

}

/* JavaCC - OriginalChecksum=337bf4272f947a68ffad6a0faa218e63 (do not edit this line) */
