/* Generated By:JJTree: Do not edit this line. ASTfunctionToBytecodes.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package yal;

public
class ASTfunctionToBytecodes extends SimpleNode {
  public ASTfunctionToBytecodes(int id) {
    super(id);
  }

  public ASTfunctionToBytecodes(yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0dd98b91bf4102ddbbeed3d97c26e1ef (do not edit this line) */
