/* Generated By:JJTree: Do not edit this line. ASTfunctionToBytecodes.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package yal;

public
class ASTfunctionToBytecodes extends SimpleNode {
  public ASTfunctionToBytecodes(int id) {
    super(id);
  }

  public ASTfunctionToBytecodes(yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=91ba5a3602bdfb96cf24c82b7ffe6ba7 (do not edit this line) */
