/* Generated By:JJTree: Do not edit this line. ASTfunctionJavaBytecodes.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package yal;

public
class ASTfunctionJavaBytecodes extends SimpleNode {
  public ASTfunctionJavaBytecodes(int id) {
    super(id);
  }

  public ASTfunctionJavaBytecodes(yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=aff0090a7f9b8245a18a9d15720025ba (do not edit this line) */
