/* Generated By:JJTree: Do not edit this line. ASTgetTypeOfTerm.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package yal;

public
class ASTgetTypeOfTerm extends SimpleNode {
  public ASTgetTypeOfTerm(int id) {
    super(id);
  }

  public ASTgetTypeOfTerm(yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5d4401633b3fa40bded0594cdc58ee27 (do not edit this line) */
