/* Generated By:JJTree: Do not edit this line. ASTgetChildren.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package yal; 

public
class ASTgetChildren extends SimpleNode {
  public ASTgetChildren(int id) {
    super(id);
  }

  public ASTgetChildren(yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=83f3751bcb481acfde3c8797fd7345bb (do not edit this line) */
