/* Generated By:JJTree: Do not edit this line. ASTgenerateSymbolTable.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package yal;

public
class ASTgenerateSymbolTable extends SimpleNode {
  public ASTgenerateSymbolTable(int id) {
    super(id);
  }

  public ASTgenerateSymbolTable(yal2jvm p, int id) {
    super(p, id);
  }

}

/* JavaCC - OriginalChecksum=3e9ed60fb55f88819617204997ac94db (do not edit this line) */
