/* Generated By:JJTree: Do not edit this line. ASTloadIntegerToBytecodes.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package yal;

public
class ASTloadIntegerToBytecodes extends SimpleNode {
  public ASTloadIntegerToBytecodes(int id) {
    super(id);
  }

  public ASTloadIntegerToBytecodes(yal2jvm p, int id) {
    super(p, id);
  }

}

/* JavaCC - OriginalChecksum=a67923960ed2d754491bbdf3cb52ab7b (do not edit this line) */