/* Generated By:JJTree: Do not edit this line. ASTmoduleJavaBytecodes.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package yal;

public
class ASTmoduleJavaBytecodes extends SimpleNode {
  public ASTmoduleJavaBytecodes(int id) {
    super(id);
  }

  public ASTmoduleJavaBytecodes(yal2jvm p, int id) {
    super(p, id);
  }

}

/* JavaCC - OriginalChecksum=eae05e9908ccdbd652299f2efac3a378 (do not edit this line) */