/* Generated By:JJTree: Do not edit this line. ASTRhs.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package yal; 

public
class ASTRhs extends SimpleNode {
  public ASTRhs(int id) {
    super(id);
  }

  public ASTRhs(yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9ef73bbef373ecc039dea5d9d7292d82 (do not edit this line) */
