/* Generated By:JJTree: Do not edit this line. ASTrhsJavaBytecodes.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package yal;

public
class ASTrhsJavaBytecodes extends SimpleNode {
  public ASTrhsJavaBytecodes(int id) {
    super(id);
  }

  public ASTrhsJavaBytecodes(yal2jvm p, int id) {
    super(p, id);
  }

}

/* JavaCC - OriginalChecksum=59e7447627c16b67aada61bb1734baba (do not edit this line) */