/* Generated By:JJTree: Do not edit this line. ASTsquaredFrame.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package yal;

public
class ASTsquaredFrame extends SimpleNode {
  public ASTsquaredFrame(int id) {
    super(id);
  }

  public ASTsquaredFrame(yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=84e73d8c4713b2b0ed87975b234654f8 (do not edit this line) */
