/* Generated By:JJTree: Do not edit this line. ASTstatementJavaBytecodes.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package yal;

public
class ASTstatementJavaBytecodes extends SimpleNode {
  public ASTstatementJavaBytecodes(int id) {
    super(id);
  }

  public ASTstatementJavaBytecodes(yal2jvm p, int id) {
    super(p, id);
  }

}

/* JavaCC - OriginalChecksum=f38a562aff2d97bd2810908336840441 (do not edit this line) */
