/* Generated By:JJTree: Do not edit this line. ASTtermJavaBytecodes.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package yal;

public
class ASTtermJavaBytecodes extends SimpleNode {
  public ASTtermJavaBytecodes(int id) {
    super(id);
  }

  public ASTtermJavaBytecodes(yal2jvm p, int id) {
    super(p, id);
  }

}

/* JavaCC - OriginalChecksum=b36fb7d84a268cfc898664b3b5a76334 (do not edit this line) */
