/* Generated By:JJTree: Do not edit this line. ASTtypeToBytecodes.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package yal;

public
class ASTtypeToBytecodes extends SimpleNode {
  public ASTtypeToBytecodes(int id) {
    super(id);
  }

  public ASTtypeToBytecodes(yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3a65c123fa68ed07639c3dc48faf47c2 (do not edit this line) */
