/* Generated By:JJTree: Do not edit this line. ASTupdateSymbolTableFunctionAssigns.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package yal;

public
class ASTupdateSymbolTableFunctionAssigns extends SimpleNode {
  public ASTupdateSymbolTableFunctionAssigns(int id) {
    super(id);
  }

  public ASTupdateSymbolTableFunctionAssigns(yal2jvm p, int id) {
    super(p, id);
  }

}

/* JavaCC - OriginalChecksum=fd5aec1c8790a5247b7c16e77e3058e9 (do not edit this line) */