/* Generated By:JJTree: Do not edit this line. ASTupdateSymbolTableFunctionStatements.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package yal;

public
class ASTupdateSymbolTableFunctionStatements extends SimpleNode {
  public ASTupdateSymbolTableFunctionStatements(int id) {
    super(id);
  }

  public ASTupdateSymbolTableFunctionStatements(yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e4a58dad1f41ec8917c3e63c1b206f19 (do not edit this line) */
