/* Generated By:JJTree: Do not edit this line. ASTupdateSymbolTableFunctionArguments.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package yal;

public
class ASTupdateSymbolTableFunctionArguments extends SimpleNode {
  public ASTupdateSymbolTableFunctionArguments(int id) {
    super(id);
  }

  public ASTupdateSymbolTableFunctionArguments(yal2jvm p, int id) {
    super(p, id);
  }

}

/* JavaCC - OriginalChecksum=b5a4ce5e3b4d45bf2ea4cdf723ec9751 (do not edit this line) */
