/* Generated By:JJTree: Do not edit this line. ASTupdateNullTypesFunctionCalls.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package yal;

public
class ASTupdateNullTypesFunctionCalls extends SimpleNode {
  public ASTupdateNullTypesFunctionCalls(int id) {
    super(id);
  }

  public ASTupdateNullTypesFunctionCalls(yal2jvm p, int id) {
    super(p, id);
  }

}

/* JavaCC - OriginalChecksum=f7d2232adfa3f0fceee3bc77580dfb76 (do not edit this line) */