/* Generated By:JJTree: Do not edit this line. ASTArgumentList.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTArgumentList extends SimpleNode {
  public ASTArgumentList(int id) {
    super(id);
  }

  public ASTArgumentList(yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=133338c37250086d2b74ba61d4e2b6a0 (do not edit this line) */
