/* Generated By:JJTree: Do not edit this line. ASTArrayElement2.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTArrayElement2 extends SimpleNode {
  public ASTArrayElement2(int id) {
    super(id);
  }

  public ASTArrayElement2(yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d487b89aa944c6072d1079d4cf5b6d9f (do not edit this line) */
