/* Generated By:JJTree: Do not edit this line. ASTArrayAccess.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
 

public
class ASTArrayAccess extends SimpleNode {
  public ASTArrayAccess(int id) {
    super(id);
  }

  public ASTArrayAccess(yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5a0c716c460ee46186c8e98de341275a (do not edit this line) */
