/* Generated By:JJTree: Do not edit this line. ASTArrayElement.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
 

public
class ASTArrayElement extends SimpleNode {
  public ASTArrayElement(int id) {
    super(id);
  }

  public ASTArrayElement(yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=59b3833297ffd89872d511a3afcd0c03 (do not edit this line) */
