/* Generated By:JJTree: Do not edit this line. ASTArraySize.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTArraySize extends SimpleNode {
  public ASTArraySize(int id) {
    super(id);
  }

  public ASTArraySize(yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c4318b2acde8209002d1d002757fa79c (do not edit this line) */
