/* Generated By:JJTree: Do not edit this line. ASTArgument.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTArgument extends SimpleNode {
  public ASTArgument(int id) {
    super(id);
  }

  public ASTArgument(yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d2638fa1f0291be88a180de9cd259fba (do not edit this line) */
