/* Generated By:JJTree: Do not edit this line. ASTcheckReturnVariable.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTcheckReturnVariable extends SimpleNode {
  public ASTcheckReturnVariable(int id) {
    super(id);
  }

  public ASTcheckReturnVariable(yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0f3a43a88034fe7f4836c1738d7fa780 (do not edit this line) */
