/* Generated By:JJTree: Do not edit this line. ASTCall.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTCall extends SimpleNode {
  public ASTCall(int id) {
    super(id);
  }

  public ASTCall(yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2fdf88666066eedb1b7937dbbc2cd601 (do not edit this line) */
