/* Generated By:JJTree: Do not edit this line. ASTcheckReturnVariable.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTcheckReturnVariable extends SimpleNode {
  public ASTcheckReturnVariable(int id) {
    super(id);
  }

  public ASTcheckReturnVariable(yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d43ec6051382a9d3f2cf71748cc96829 (do not edit this line) */
