/* Generated By:JJTree: Do not edit this line. ASTcheckDuplicates.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTcheckDuplicates extends SimpleNode {
  public ASTcheckDuplicates(int id) {
    super(id);
  }

  public ASTcheckDuplicates(yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4b940f0e9a2515a7d8e3b09360057f1e (do not edit this line) */
