/* Generated By:JJTree: Do not edit this line. ASTclinitJavaBytecodes.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTclinitJavaBytecodes extends SimpleNode {
  public ASTclinitJavaBytecodes(int id) {
    super(id);
  }

  public ASTclinitJavaBytecodes(yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=26bd18d3664d65c6125cc415fa155970 (do not edit this line) */
