/* Generated By:JJTree: Do not edit this line. ASTcheckArgsAreNotGlobals.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTcheckArgsAreNotGlobals extends SimpleNode {
  public ASTcheckArgsAreNotGlobals(int id) {
    super(id);
  }

  public ASTcheckArgsAreNotGlobals(yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=17c9749392ab9b55519fc2f899992390 (do not edit this line) */
