/* Generated By:JJTree: Do not edit this line. ASTclinitJavaBytecodes.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTclinitJavaBytecodes extends SimpleNode {
  public ASTclinitJavaBytecodes(int id) {
    super(id);
  }

  public ASTclinitJavaBytecodes(yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c6299a38e37eecf80af8042868c8cd09 (do not edit this line) */
