/* Generated By:JJTree: Do not edit this line. ASTcheckArgsAreNotGlobals.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTcheckArgsAreNotGlobals extends SimpleNode {
  public ASTcheckArgsAreNotGlobals(int id) {
    super(id);
  }

  public ASTcheckArgsAreNotGlobals(yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=fc7361356d090ca40f661c7fa0120d3e (do not edit this line) */
