/* Generated By:JJTree: Do not edit this line. ASTdeclarationJavaByteCodes.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTdeclarationJavaByteCodes extends SimpleNode {
  public ASTdeclarationJavaByteCodes(int id) {
    super(id);
  }

  public ASTdeclarationJavaByteCodes(yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4178ae3bb783f0f700d4a7059fff4add (do not edit this line) */
