/* Generated By:JJTree: Do not edit this line. ASTElement.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTElement extends SimpleNode {
  public ASTElement(int id) {
    super(id);
  }

  public ASTElement(yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=84cd7c4d7e27dbdf5d5cc3dca217fdb9 (do not edit this line) */
