/* Generated By:JJTree: Do not edit this line. ASTExprtest.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
 

public
class ASTExprtest extends SimpleNode {
  public ASTExprtest(int id) {
    super(id);
  }

  public ASTExprtest(yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8dde3c8421fa9d98e6ea82a70f1edf6c (do not edit this line) */
