/* Generated By:JJTree: Do not edit this line. ASTfunctionToBytecodes.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTfunctionToBytecodes extends SimpleNode {
  public ASTfunctionToBytecodes(int id) {
    super(id);
  }

  public ASTfunctionToBytecodes(yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=154ffb5d8db6ac3054c151975a2d7a97 (do not edit this line) */
