/* Generated By:JJTree: Do not edit this line. ASTfunctionJavaBytecodes.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTfunctionJavaBytecodes extends SimpleNode {
  public ASTfunctionJavaBytecodes(int id) {
    super(id);
  }

  public ASTfunctionJavaBytecodes(yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ed35e0414619bcea22030d17ebe32a50 (do not edit this line) */
