/* Generated By:JJTree: Do not edit this line. ASTfunctionCallJavaBytecodes.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTfunctionCallJavaBytecodes extends SimpleNode {
  public ASTfunctionCallJavaBytecodes(int id) {
    super(id);
  }

  public ASTfunctionCallJavaBytecodes(yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2fae63d18d8865d5b08df719191d88f4 (do not edit this line) */
