/* Generated By:JJTree: Do not edit this line. ASTfunctionCallJavaBytecodes.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTfunctionCallJavaBytecodes extends SimpleNode {
  public ASTfunctionCallJavaBytecodes(int id) {
    super(id);
  }

  public ASTfunctionCallJavaBytecodes(yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=86871dbea709f53a50a9273e5b0e082c (do not edit this line) */
