/* Generated By:JJTree: Do not edit this line. ASTfunctionJavaBytecodes.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTfunctionJavaBytecodes extends SimpleNode {
  public ASTfunctionJavaBytecodes(int id) {
    super(id);
  }

  public ASTfunctionJavaBytecodes(yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ce29eccbc2c604d9f924a87c123d4315 (do not edit this line) */
