/* Generated By:JJTree: Do not edit this line. ASTgenerateSymbolTable.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTgenerateSymbolTable extends SimpleNode {
  public ASTgenerateSymbolTable(int id) {
    super(id);
  }

  public ASTgenerateSymbolTable(yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d065b7516aa1eb3ba826d91d16483543 (do not edit this line) */
