/* Generated By:JJTree: Do not edit this line. ASTgenerateSymbolTable.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTgenerateSymbolTable extends SimpleNode {
  public ASTgenerateSymbolTable(int id) {
    super(id);
  }

  public ASTgenerateSymbolTable(yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b6830a6580428bb13761eba3694dd71b (do not edit this line) */
