/* Generated By:JJTree: Do not edit this line. ASTgenerateJavaBytecodes.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTgenerateJavaBytecodes extends SimpleNode {
  public ASTgenerateJavaBytecodes(int id) {
    super(id);
  }

  public ASTgenerateJavaBytecodes(yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1cefee4451f3013b78eabeba9c5e1ad4 (do not edit this line) */
