/* Generated By:JJTree: Do not edit this line. ASTgenerateSymbolTable.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTgenerateSymbolTable extends SimpleNode {
  public ASTgenerateSymbolTable(int id) {
    super(id);
  }

  public ASTgenerateSymbolTable(yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=efed3db44f1b0fe8f5662fa717ff7d95 (do not edit this line) */
