/* Generated By:JJTree: Do not edit this line. ASTincErrorCounter.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTincErrorCounter extends SimpleNode {
  public ASTincErrorCounter(int id) {
    super(id);
  }

  public ASTincErrorCounter(yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d05420711ff7f6d5bab925f3625ef79f (do not edit this line) */
