/* Generated By:JJTree: Do not edit this line. ASTIndex.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
 

public
class ASTIndex extends SimpleNode {
  public ASTIndex(int id) {
    super(id);
  }

  public ASTIndex(yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=31580b7626fb5e90b07c55718c10b264 (do not edit this line) */
