/* Generated By:JJTree: Do not edit this line. ASTincErrorCounter.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
 

public
class ASTincErrorCounter extends SimpleNode {
  public ASTincErrorCounter(int id) {
    super(id);
  }

  public ASTincErrorCounter(yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b2820460a3a88132e108e2d87b03c42e (do not edit this line) */
