/* Generated By:JJTree: Do not edit this line. ASTloadIntegerToBytecodes.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTloadIntegerToBytecodes extends SimpleNode {
  public ASTloadIntegerToBytecodes(int id) {
    super(id);
  }

  public ASTloadIntegerToBytecodes(yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d087b412fa01dfac5b6811b4f33229ec (do not edit this line) */
