/* Generated By:JJTree: Do not edit this line. ASTLhsArraySize.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTLhsArraySize extends SimpleNode {
  public ASTLhsArraySize(int id) {
    super(id);
  }

  public ASTLhsArraySize(yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1304f72fb96dd583b3cd99d40e7a879b (do not edit this line) */
