/* Generated By:JJTree: Do not edit this line. ASTloadIntegerToBytecodes.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTloadIntegerToBytecodes extends SimpleNode {
  public ASTloadIntegerToBytecodes(int id) {
    super(id);
  }

  public ASTloadIntegerToBytecodes(yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=44fa3678496e00add0905ace8ed8c6a9 (do not edit this line) */
