/* Generated By:JJTree: Do not edit this line. ASTloadIntegerToBytecodes.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTloadIntegerToBytecodes extends SimpleNode {
  public ASTloadIntegerToBytecodes(int id) {
    super(id);
  }

  public ASTloadIntegerToBytecodes(yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=29e542d6513073e084a32a0d11c68e0c (do not edit this line) */
