/* Generated By:JJTree: Do not edit this line. ASTLhs.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
 

public
class ASTLhs extends SimpleNode {
  public ASTLhs(int id) {
    super(id);
  }

  public ASTLhs(yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=29132519e08d5fa132c56faf72285110 (do not edit this line) */
