/* Generated By:JJTree: Do not edit this line. ASTModule.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTModule extends SimpleNode {
  public ASTModule(int id) {
    super(id);
  }

  public ASTModule(yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=54cf925213a34f271395ff16ae5d0961 (do not edit this line) */
