/* Generated By:JJTree: Do not edit this line. ASTmoduleJavaBytecodes.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTmoduleJavaBytecodes extends SimpleNode {
  public ASTmoduleJavaBytecodes(int id) {
    super(id);
  }

  public ASTmoduleJavaBytecodes(yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=bc0006171f5584194320660bf476bb57 (do not edit this line) */
