/* Generated By:JJTree: Do not edit this line. ASTmoduleJavaBytecodes.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTmoduleJavaBytecodes extends SimpleNode {
  public ASTmoduleJavaBytecodes(int id) {
    super(id);
  }

  public ASTmoduleJavaBytecodes(yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b3d637f297b2fae96c46f891ea7b6b0c (do not edit this line) */
