/* Generated By:JJTree: Do not edit this line. ASTRhs.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTRhs extends SimpleNode {
  public ASTRhs(int id) {
    super(id);
  }

  public ASTRhs(yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0932c4d8e8dbee6d3d9afe348e47f01b (do not edit this line) */
