/* Generated By:JJTree: Do not edit this line. ASTrhsJavaBytecodes.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTrhsJavaBytecodes extends SimpleNode {
  public ASTrhsJavaBytecodes(int id) {
    super(id);
  }

  public ASTrhsJavaBytecodes(yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1431577986403b97a615f44f1494b26f (do not edit this line) */
