/* Generated By:JJTree: Do not edit this line. ASTScalarElement.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
 

public
class ASTScalarElement extends SimpleNode {
  public ASTScalarElement(int id) {
    super(id);
  }

  public ASTScalarElement(yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b998c8fa1b8c8eac94c7ff7f32145e1d (do not edit this line) */
