/* Generated By:JJTree: Do not edit this line. ASTstatementJavaBytecodes.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTstatementJavaBytecodes extends SimpleNode {
  public ASTstatementJavaBytecodes(int id) {
    super(id);
  }

  public ASTstatementJavaBytecodes(yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d330da754e8349b63df225fce1c64093 (do not edit this line) */
