/* Generated By:JJTree: Do not edit this line. ASTstatementJavaBytecodes.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTstatementJavaBytecodes extends SimpleNode {
  public ASTstatementJavaBytecodes(int id) {
    super(id);
  }

  public ASTstatementJavaBytecodes(yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b80b8c9e1e55d9f9e75142a422fbe646 (do not edit this line) */
