/* Generated By:JJTree: Do not edit this line. ASTStmt.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTStmt extends SimpleNode {
  public ASTStmt(int id) {
    super(id);
  }

  public ASTStmt(yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=dd0e12151bd996d245a0a43af59c0e95 (do not edit this line) */
