/* Generated By:JJTree: Do not edit this line. ASTStmtlst.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
 

public
class ASTStmtlst extends SimpleNode {
  public ASTStmtlst(int id) {
    super(id);
  }

  public ASTStmtlst(yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=38af23cdce4f2385d3a9f8ac6115eb38 (do not edit this line) */
