/* Generated By:JJTree: Do not edit this line. ASTScalarAccess.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTScalarAccess extends SimpleNode {
  public ASTScalarAccess(int id) {
    super(id);
  }

  public ASTScalarAccess(yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4d994534fb99289e9bec02781d6701a6 (do not edit this line) */
