/* Generated By:JJTree: Do not edit this line. ASTstatementJavaBytecodes.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTstatementJavaBytecodes extends SimpleNode {
  public ASTstatementJavaBytecodes(int id) {
    super(id);
  }

  public ASTstatementJavaBytecodes(yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f1b2db07c59de76a3ad15c85f9390871 (do not edit this line) */
