/* Generated By:JJTree: Do not edit this line. ASTtypeToStr.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTtypeToStr extends SimpleNode {
  public ASTtypeToStr(int id) {
    super(id);
  }

  public ASTtypeToStr(yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4877b9e1495a45cb7251b9953d663438 (do not edit this line) */
