/* Generated By:JJTree: Do not edit this line. ASTtermJavaBytecodes.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTtermJavaBytecodes extends SimpleNode {
  public ASTtermJavaBytecodes(int id) {
    super(id);
  }

  public ASTtermJavaBytecodes(yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f16ac67997a1d49b078284f096027a2a (do not edit this line) */
