/* Generated By:JJTree: Do not edit this line. ASTtermJavaBytecodes.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTtermJavaBytecodes extends SimpleNode {
  public ASTtermJavaBytecodes(int id) {
    super(id);
  }

  public ASTtermJavaBytecodes(yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=82078670ac4a5ec9a4e3e6bc054d50ef (do not edit this line) */
