/* Generated By:JJTree: Do not edit this line. ASTtermJavaBytecodes.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTtermJavaBytecodes extends SimpleNode {
  public ASTtermJavaBytecodes(int id) {
    super(id);
  }

  public ASTtermJavaBytecodes(yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d07f2007ad57c1ed35ce0963286c7cb3 (do not edit this line) */
