/* Generated By:JJTree: Do not edit this line. ASTtypeToBytecodes.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTtypeToBytecodes extends SimpleNode {
  public ASTtypeToBytecodes(int id) {
    super(id);
  }

  public ASTtypeToBytecodes(yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=87fd359be833a1a2ae6c717cea569c4a (do not edit this line) */
