/* Generated By:JJTree: Do not edit this line. ASTtypeToBytecodes.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTtypeToBytecodes extends SimpleNode {
  public ASTtypeToBytecodes(int id) {
    super(id);
  }

  public ASTtypeToBytecodes(yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=40dd8c666b304a6d6244f299e2248c26 (do not edit this line) */
