/* Generated By:JJTree: Do not edit this line. ASTupdateNullTypesFunctionCalls.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTupdateNullTypesFunctionCalls extends SimpleNode {
  public ASTupdateNullTypesFunctionCalls(int id) {
    super(id);
  }

  public ASTupdateNullTypesFunctionCalls(yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=fdae92c0242b0e4a080eb96db5771a6d (do not edit this line) */
