/* Generated By:JJTree: Do not edit this line. ASTupdateSymbolTableFunctionArguments.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTupdateSymbolTableFunctionArguments extends SimpleNode {
  public ASTupdateSymbolTableFunctionArguments(int id) {
    super(id);
  }

  public ASTupdateSymbolTableFunctionArguments(yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0e1f76db428acd4737eeba88238cc5be (do not edit this line) */
