/* Generated By:JJTree: Do not edit this line. ASTupdateNullTypesFunctionCalls.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTupdateNullTypesFunctionCalls extends SimpleNode {
  public ASTupdateNullTypesFunctionCalls(int id) {
    super(id);
  }

  public ASTupdateNullTypesFunctionCalls(yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=fc709d506738db4bd495144ec5921384 (do not edit this line) */
