/* Generated By:JJTree: Do not edit this line. ASTupdateSymbolTableFunctionAssigns.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTupdateSymbolTableFunctionAssigns extends SimpleNode {
  public ASTupdateSymbolTableFunctionAssigns(int id) {
    super(id);
  }

  public ASTupdateSymbolTableFunctionAssigns(yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=df0d3f23967066c59a7f9716089d59d8 (do not edit this line) */
