/* Generated By:JJTree: Do not edit this line. ASTupdateSymbolTableFunctionAssigns.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTupdateSymbolTableFunctionAssigns extends SimpleNode {
  public ASTupdateSymbolTableFunctionAssigns(int id) {
    super(id);
  }

  public ASTupdateSymbolTableFunctionAssigns(yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=759f5372344264ff3f66e05cee308e48 (do not edit this line) */
