/* Generated By:JJTree: Do not edit this line. ASTupdateSymbolTableFunctionStatements.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTupdateSymbolTableFunctionStatements extends SimpleNode {
  public ASTupdateSymbolTableFunctionStatements(int id) {
    super(id);
  }

  public ASTupdateSymbolTableFunctionStatements(yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=324025f71fe40d5593294f3b41b6c1f1 (do not edit this line) */
