/* Generated By:JJTree: Do not edit this line. ASTupdateSymbolTableForFunction.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTupdateSymbolTableForFunction extends SimpleNode {
  public ASTupdateSymbolTableForFunction(int id) {
    super(id);
  }

  public ASTupdateSymbolTableForFunction(yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=758da40a7d0770263b3ac1287c1dfa6f (do not edit this line) */
