/* Generated By:JJTree: Do not edit this line. ASTupdateNullTypes.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTupdateNullTypes extends SimpleNode {
  public ASTupdateNullTypes(int id) {
    super(id);
  }

  public ASTupdateNullTypes(yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=22a862c1d406035429710c80af387189 (do not edit this line) */
