/* Generated By:JJTree: Do not edit this line. ASTupdateSymbolTableFunctionArguments.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTupdateSymbolTableFunctionArguments extends SimpleNode {
  public ASTupdateSymbolTableFunctionArguments(int id) {
    super(id);
  }

  public ASTupdateSymbolTableFunctionArguments(yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=05ec74178b6a0d4a271bb7ec1dd32985 (do not edit this line) */
