/* Generated By:JJTree: Do not edit this line. ASTupdateSymbolTableFunctionFunctionCalls.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTupdateSymbolTableFunctionFunctionCalls extends SimpleNode {
  public ASTupdateSymbolTableFunctionFunctionCalls(int id) {
    super(id);
  }

  public ASTupdateSymbolTableFunctionFunctionCalls(yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=981d23e0c6f67726b7e614cbb06c7940 (do not edit this line) */
