/* Generated By:JJTree: Do not edit this line. ASTupdateSymbolTableFunctionAssigns.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTupdateSymbolTableFunctionAssigns extends SimpleNode {
  public ASTupdateSymbolTableFunctionAssigns(int id) {
    super(id);
  }

  public ASTupdateSymbolTableFunctionAssigns(yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b74a141804103d2ce37c5c839e028131 (do not edit this line) */
