/* Generated By:JJTree: Do not edit this line. ASTupdateSymbolTableFunctionStatements.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTupdateSymbolTableFunctionStatements extends SimpleNode {
  public ASTupdateSymbolTableFunctionStatements(int id) {
    super(id);
  }

  public ASTupdateSymbolTableFunctionStatements(yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=30cccab6d57f576bb9ba8b6fa1ccd74c (do not edit this line) */
