/* Generated By:JJTree: Do not edit this line. ASTVarlist.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTVarlist extends SimpleNode {
  public ASTVarlist(int id) {
    super(id);
  }

  public ASTVarlist(yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a00a1e35e3bec844ae40f701d1703fe5 (do not edit this line) */
