/* Generated By:JJTree: Do not edit this line. ASTwhileJavaBytecodes.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTwhileJavaBytecodes extends SimpleNode {
  public ASTwhileJavaBytecodes(int id) {
    super(id);
  }

  public ASTwhileJavaBytecodes(yal2jvm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ff410f64394db6a47e52d9a36742f15b (do not edit this line) */
