/* Generated By:JavaCC: Do not edit this line. yal2jvmTreeConstants.java Version 6.0_1 */
public interface yal2jvmTreeConstants
{
  public int JJTMODULE = 0;
  public int JJTDECLARATION = 1;
  public int JJTFUNCTION = 2;
  public int JJTVARLIST = 3;
  public int JJTARRAYELEMENT = 4;
  public int JJTELEMENT = 5;
  public int JJTSCALARELEMENT = 6;
  public int JJTSTMTLST = 7;
  public int JJTVOID = 8;
  public int JJTSTMT = 9;
  public int JJTASSIGN = 10;
  public int JJTLHS = 11;
  public int JJTRHS = 12;
  public int JJTARRAYSIZE = 13;
  public int JJTTERM = 14;
  public int JJTEXPRTEST = 15;
  public int JJTWHILE = 16;
  public int JJTIF = 17;
  public int JJTCALL = 18;
  public int JJTARGUMENTLIST = 19;
  public int JJTARGUMENT = 20;
  public int JJTARRAYACCESS = 21;
  public int JJTSCALARACCESS = 22;
  public int JJTINDEX = 23;
  public int JJTINCERRORCOUNTER = 24;
  public int JJTGENERATEJAVABYTECODES = 25;
  public int JJTMODULEJAVABYTECODES = 26;
  public int JJTFUNCTIONJAVABYTECODES = 27;
  public int JJTSTATEMENTJAVABYTECODES = 28;
  public int JJTRHSJAVABYTECODES = 29;
  public int JJTTERMJAVABYTECODES = 30;
  public int JJTTYPETOBYTECODES = 31;
  public int JJTFUNCTIONTOBYTECODES = 32;
  public int JJTLOADINTEGERTOBYTECODES = 33;
  public int JJTCLINITJAVABYTECODES = 34;
  public int JJTGENERATESYMBOLTABLE = 35;
  public int JJTUPDATESYMBOLTABLEFUNCTIONARGUMENTS = 36;
  public int JJTUPDATESYMBOLTABLEFUNCTIONSTATEMENTS = 37;
  public int JJTUPDATESYMBOLTABLEFUNCTIONFUNCTIONCALLS = 38;
  public int JJTUPDATENULLTYPESFUNCTIONCALLS = 39;


  public String[] jjtNodeName = {
    "Module",
    "Declaration",
    "Function",
    "Varlist",
    "ArrayElement",
    "Element",
    "ScalarElement",
    "Stmtlst",
    "void",
    "Stmt",
    "Assign",
    "Lhs",
    "Rhs",
    "ArraySize",
    "Term",
    "Exprtest",
    "While",
    "If",
    "Call",
    "ArgumentList",
    "Argument",
    "ArrayAccess",
    "ScalarAccess",
    "Index",
    "incErrorCounter",
    "generateJavaBytecodes",
    "moduleJavaBytecodes",
    "functionJavaBytecodes",
    "statementJavaBytecodes",
    "rhsJavaBytecodes",
    "termJavaBytecodes",
    "typeToBytecodes",
    "functionToBytecodes",
    "loadIntegerToBytecodes",
    "clinitJavaBytecodes",
    "generateSymbolTable",
    "updateSymbolTableFunctionArguments",
    "updateSymbolTableFunctionStatements",
    "updateSymbolTableFunctionFunctionCalls",
    "updateNullTypesFunctionCalls",
  };
}
/* JavaCC - OriginalChecksum=d993bf60c0ec61b344ada6306ba6b40a (do not edit this line) */
