/* Generated By:JavaCC: Do not edit this line. yal2jvmTreeConstants.java Version 6.0_1 */
public interface yal2jvmTreeConstants
{
  public int JJTMODULE = 0;
  public int JJTDECLARATION = 1;
  public int JJTFUNCTION = 2;
  public int JJTVARLIST = 3;
  public int JJTARRAYELEMENT = 4;
  public int JJTELEMENT = 5;
  public int JJTSCALARELEMENT = 6;
  public int JJTSTMTLST = 7;
  public int JJTVOID = 8;
  public int JJTSTMT = 9;
  public int JJTASSIGN = 10;
  public int JJTLHS = 11;
  public int JJTLHSARRAYSIZE = 12;
  public int JJTRHS = 13;
  public int JJTARRAYSIZE = 14;
  public int JJTTERM = 15;
  public int JJTEXPRTEST = 16;
  public int JJTWHILE = 17;
  public int JJTIF = 18;
  public int JJTCALL = 19;
  public int JJTARGUMENTLIST = 20;
  public int JJTARGUMENT = 21;
  public int JJTARRAYACCESS = 22;
  public int JJTSCALARACCESS = 23;
  public int JJTINDEX = 24;
  public int JJTINCERRORCOUNTER = 25;
  public int JJTGENERATESYMBOLTABLE = 26;
  public int JJTUPDATESYMBOLTABLEFUNCTIONARGUMENTS = 27;
  public int JJTUPDATESYMBOLTABLEFUNCTIONSTATEMENTS = 28;
  public int JJTUPDATESYMBOLTABLEFUNCTIONFUNCTIONCALLS = 29;
  public int JJTUPDATENULLTYPESFUNCTIONCALLS = 30;


  public String[] jjtNodeName = {
    "Module",
    "Declaration",
    "Function",
    "Varlist",
    "ArrayElement",
    "Element",
    "ScalarElement",
    "Stmtlst",
    "void",
    "Stmt",
    "Assign",
    "Lhs",
    "LhsArraySize",
    "Rhs",
    "ArraySize",
    "Term",
    "Exprtest",
    "While",
    "If",
    "Call",
    "ArgumentList",
    "Argument",
    "ArrayAccess",
    "ScalarAccess",
    "Index",
    "incErrorCounter",
    "generateSymbolTable",
    "updateSymbolTableFunctionArguments",
    "updateSymbolTableFunctionStatements",
    "updateSymbolTableFunctionFunctionCalls",
    "updateNullTypesFunctionCalls",
  };
}
/* JavaCC - OriginalChecksum=4f341d182f80233a882ed281d51dd9c0 (do not edit this line) */
